### ISSUE TITLE
Make `loop` fixture as alias for `event_loop`

### ISSUE THREAD

**Issue by asvetlov** [pytest-dev/pytest-asyncio#12]
In asyncio world parameter for event loop is always called `loop`, never `event_loop`.
I think we should use the same name for fixture (with keeping backward compatibility, sure).

Also disabling global loop by `asyncio.set_event_loop(None)` is useful feature.
I always run my tests in isolated environment.
Global loop may be an option (nondefault) for `loop` fixture. 
`event_loop` should preserve existing global strategy but may accept option for disabling it (or we may keep it untouched encouraging people to use `loop` fixture).

**Comment by jettify** [comment]
any updates about this issue? Probably it is possible o add something like:
```python
@pytest.fixture
def loop(event_loop):
   return event_loop
```

**Comment by dimaqq** [comment]
IMO `loop` is too generic for a magic name that pops up simple because one more testing library is installed.
Proposed work-around is simple enough.

Ultimately the preferred/advertised way to test is `@pytest.mark.asyncio  async def test_something()` and (perhaps) direct use of `event_loop` is rare?
