### ISSUE TITLE
Bug when setting context var in test

### ISSUE THREAD

**Issue by masipcat** [pytest-dev/pytest-asyncio#149]
```python 
import asyncio
import pytest
from contextvars import ContextVar

var = ContextVar("var")


@pytest.mark.asyncio
async def test_context_var_fails():
    var.set("hi")
    print("", id(asyncio.current_task()))

    async def read_var():
        print("read_var", id(asyncio.current_task()))
        return var.get(None)

    val = await asyncio.create_task(read_var())
    # I expect `val` to be `None` but it's value is `"hi"`
    assert val is None


@pytest.mark.asyncio
async def test_context_var_works():
    async def set_ctxvar(val):
        global var
        print("set_ctxvar", id(asyncio.current_task()))
        var.set(val)

    await asyncio.create_task(set_ctxvar("hi"))

    async def read_var():
        global var
        print("read_var", id(asyncio.current_task()))
        return var.get(None)

    val = await asyncio.create_task(read_var())
    assert val is None
```

The stdout is:
```
================================== test session starts ===================================
platform linux -- Python 3.7.1, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/jordi/gits/api, inifile: pytest.ini
plugins: asyncio-0.10.0, flaky-3.6.1
collected 2 items                                                                        

test_contextvars.py F.                                                             [100%]

======================================== FAILURES ========================================
_________________________________ test_context_var_fails _________________________________

    @pytest.mark.asyncio
    async def test_context_var_fails():
        var.set("hi")
        print("", id(asyncio.current_task()))
    
        async def read_var():
            print("read_var", id(asyncio.current_task()))
            return var.get(None)
    
        val = await asyncio.create_task(read_var())
        # I expect `val` to be `None` but it's `"hi"`
>       assert val is None
E       AssertionError: assert 'hi' is None

test_contextvars.py:19: AssertionError
---------------------------------- Captured stdout call ----------------------------------
 140184898681256
read_var 140184898680616
============================== 1 failed, 1 passed in 0.04s ===============================
```

**Comment by dmitrypolo** [comment]
This doesn't appear to be a bug to me. The variable `var` is still visible in the `read_var` scope, since it has been defined within `test_context_var_fails`. Try your example without `asyncio`, it won't work regardless. The variable `var` will be available within any function defined inside of `test_context_var_fails`.

**Comment by masipcat** [comment]
> This doesn't appear to be a bug to me. The variable var is still visible in the read_var scope, since it has been defined within test_context_var_fails.

I rewrote the previous test and I have found something interesting:

```python
import asyncio
import pytest
from contextvars import ContextVar

var = ContextVar("var")

async def read_var():
    print("read_var", id(asyncio.current_task()))
    return var.get(None)

async def set_ctxvar(val):
    print("set_ctxvar", id(asyncio.current_task()))
    var.set(val)

@pytest.mark.asyncio
async def test_context_var_fails():
    print("set_ctxvar", id(asyncio.current_task()))
    var.set("hi")

    val = await asyncio.create_task(read_var())
    # I expect `val` to be `None` but it's value is `"hi"`
    assert val is None


@pytest.mark.asyncio
async def test_context_var_works():
    # print("set_ctxvar", id(asyncio.current_task()))
    # var.set("hi")
    set_ctxvar("hi")

    val = await asyncio.create_task(read_var())
    assert val is None  # now it works!
```

It seems that it has something to do with visibility of the variable, but I don't understand it...

> Try your example without asyncio, it won't work regardless. The variable var will be available within any function defined inside of test_context_var_fails.

I'm not sure how to test it without asyncio. Using threads?

**Comment by simonfagerholm** [comment]
@masipcat What are you actually expecting to happen?
In the first test case you synchronously set the ContextVar and then wait until the asynchronous read function is finished.
In the second test case you don't wait for the asynchronous set to happen, which gives me the warning:
```
RuntimeWarning: coroutine 'set_ctxvar' was never awaited
    set_ctxvar("hi")
```
After that you wait until the asynchronous read function is finished. Because the asynchronous set was not performed the second time you get `None` back.
If you do  `await set_ctxvar("hi")` in the second TC you get the same result in both TCs.

**Comment by masipcat** [comment]
Argg, I forgot to remove the async in set_ctxvar and didn't see the warning... 

Here is a corrected version:

```
import asyncio
import pytest
from contextvars import ContextVar


var = ContextVar("var")


async def read_var():
    print("read_var", id(asyncio.current_task()))
    return var.get(None)

async def set_ctxvar(val):
    print("set_ctxvar", id(asyncio.current_task()))
    var.set(val)


@pytest.mark.asyncio
async def test_context_var_fails():
    await set_ctxvar("hi")

    val = await asyncio.create_task(read_var())
    assert val is None  # I expect `val` to be `None` but it's value is `"hi"`


@pytest.mark.asyncio
async def test_context_var_works():
    await asyncio.create_task(set_ctxvar("hi"))

    val = await asyncio.create_task(read_var())
    assert val is None  # now it works!
```

**Comment by simonfagerholm** [comment]
@masipcat Is that not the correct behaviour? When I read the [Task object docs](https://docs.python.org/3/library/asyncio-task.html#task-object) it says

> Tasks support the contextvars module. When a Task is **created it copies the current context** and later runs its coroutine in the copied context.

I interpret this as in TC2 you have the original context, which is unaffected by `set_ctxvar`, and a copied context, that `set_ctxvar` changes. When `read_var` is executed it also copies the original context and sees no change.
In TC1 you have the original context, which is changed by `set_ctxvar` because it is not in a new Task-object. When `read_var` is executed this time it copies the original context **after** the change, thus the `read_var` sees the change.

**Comment by masipcat** [comment]
Oh, I'm sorry, I wasn't aware the create_task was copying the context to the new task. So yes, this is not a bug and is the expected behavior. 

Sorry again for bothering you!

**Comment by simonfagerholm** [comment]
@masipcat No problem, got me to read up on contextvars
