### ISSUE TITLE
Event loop in setup_method

### ISSUE THREAD

**Issue by JinKazuya** [pytest-dev/pytest-asyncio#159]
Hi,

I have many unit tests as below:

```
class TestObj:
    def setup_method(self):
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)
        self.object_under_test = Obj(event_loop=self.loop)

    def test_foo(self):
       self.loop.run_until_complete(self.objec_under_test.async_method())
```

But what I would like is to not create my own loop and have either:
- the `event_loop` injected into `setup_method`
or
- just call `asyncio.get_running_loop()` in `setup_method`

So that I could turn the test into:
```
class TestObj:
    def setup_method(self, event_loop):
        self.object_under_test = Obj(event_loop=event_loop) # or asyncio.get_running_loop()

    async def test_foo(self):
       await self.objec_under_test.async_method()
```

If this can be done I haven't been able to figured it out yet.
Any help to achieve the above or explanation as to how this cannot work is much appreciated.

**Comment by simonfagerholm** [comment]
@JinKazuya Instead of using xunit-style setup, use a setup-fixture that depends on the event_loop fixture from pytest-asyncio. Then add the `@pytest.mark.asyncio` marker to your test methods.

In some cases you can probably skip the setup-fixture entirely, like so:
```
class Test:
    @pytest.mark.asyncio
    async def test_obj(self, event_loop):
        await Obj(event_loop=event_loop).async_method()
```

**Comment by rupertcw** [comment]
@simonfagerholm Yes of course I should've mentioned the above as a possibility. 
The reason I didn't is because it is clearly sub-optimal due to the inherent repetition involved.

In the example above, the issue is not that catastrophic, but once you have more complex objects and dependency injections it would be unrealistic, error-prone and inefficient to rewrite the 'setup' code in every test.

I might've misread the README but if this library only sets up the loop per-test to ensure isolation, etc. then I'm not sure why the loop couldn't be injected into the setup (NOT setUpClass or whatever is the pytest equivalent) as it is run per-test.

**Comment by simonfagerholm** [comment]
@rupertcw Of course you don't need to put it in each test, like I say in my comment "In ***some*** cases you can probably skip the setup-fixture entire. The first part of my comment is about using a fixture to setup, which is entirely possible.

**Comment by rupertcw** [comment]
Ah, I read too quickly and assumed it was all one example :) I will have a look at setup-fixtures as you suggested. Thanks!

**Comment by JinKazuya** [comment]
@simonfagerholm worked like a charm. Thanks!

**Comment by simonfagerholm** [comment]
Great!
