### ISSUE TITLE
Release 0.14.0 yields RuntimeError: Timeout context manager should be used inside a task

### ISSUE THREAD

**Issue by CarstenLeue** [pytest-dev/pytest-asyncio#170]
I am using `pytest-asyncio` together with `pytest-aiohttp`. 

When trying to establish a client session in an async testcase I get:

```
RuntimeError: Timeout context manager should be used inside a task
```
for `pytest-asyncio` `0.14.0`. The same works with `0.12.0`

Example:

```python
from aiohttp.web import Application
from pytest import mark


@mark.asyncio
async def test_client(aiohttp_client):
    app = Application()
    client = await aiohttp_client(app)
    await client.get('/')
```

On `0.12.0` this code succeeds, on `0.14.0` it produces the following error:

```
============================================================================================ FAILURES ============================================================================================= 
_______________________________________________________________________________________ test_client[pyloop] _______________________________________________________________________________________ 

aiohttp_client = <function aiohttp_client.<locals>.go at 0x000001DBCCA19AE8>

    @mark.asyncio
    async def test_client(aiohttp_client):
        app = Application()
        client = await aiohttp_client(app)
>       await client.get('/')

test\test_asyncio.py:9:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv\lib\site-packages\aiohttp\test_utils.py:292: in _request
    method, self.make_url(path), **kwargs
.venv\lib\site-packages\aiohttp\client.py:426: in _request
    with timer:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiohttp.helpers.TimerContext object at 0x000001DBCCA26908>

    def __enter__(self) -> BaseTimerContext:
        task = current_task(loop=self._loop)

        if task is None:
>           raise RuntimeError('Timeout context manager should be used '
                               'inside a task')
E           RuntimeError: Timeout context manager should be used inside a task

.venv\lib\site-packages\aiohttp\helpers.py:579: RuntimeError
======================================================================================== warnings summary ========================================================================================= 
test/test_asyncio.py::test_client[pyloop]
  XXX\.venv\lib\site-packages\aiohttp\cookiejar.py:55: DeprecationWarning: The object should be created from async function
    super().__init__(loop=loop)

test/test_asyncio.py::test_client[pyloop]
  XXX\.venv\lib\site-packages\aiohttp\test_utils.py:251: DeprecationWarning: The object should be created from async function
    **kwargs)

test/test_asyncio.py::test_client[pyloop]
  XXX\.venv\lib\site-packages\aiohttp\connector.py:731: DeprecationWarning: The object should be created from async function
    loop=loop)

test/test_asyncio.py::test_client[pyloop]
  XXX\.venv\lib\site-packages\aiohttp\connector.py:736: DeprecationWarning: The object should be created from async function
    resolver = DefaultResolver(loop=self._loop)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================================================================== short test summary info ===================================================================================== 
FAILED test/test_asyncio.py::test_client[pyloop] - RuntimeError: Timeout context manager should be used inside a task
========================================================================== 1 failed, 10 deselected, 4 warnings in 0.83s =========================================================================== 
```

Version of `pytest-aiohttp` is `0.3.0`

**Comment by alblasco** [comment]
Thanks for your kind feedback.

@Tinche I will dig into it this weekend (and previous new issues)

**Comment by alblasco** [comment]
After some debugging with your example, I have seen the following:

1) pytest-asyncio event_loop fixture provides a new loop, using new_event_loop() & set_event_loop(). Let's call it L1:
https://github.com/pytest-dev/pytest-asyncio/blob/v0.14.0/pytest_asyncio/plugin.py#L206-L210
https://github.com/pytest-dev/pytest-asyncio/blob/v0.14.0/pytest_asyncio/plugin.py#L91
2) Then aiohttp loop fixture does also something similar, to geT a new loop. Let's call it L2:
https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/pytest_plugin.py#L213-L216
https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/test_utils.py#L517-L524

3) Then pytest-asyncio run test_client until complete, using L1 loop.
   Note: This has changed in V0.14 (in V0.12 used L2)
   
4) The error comes due to following code, 
https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/helpers.py#L570-L580
that keeps using L2 loop, and fails due to that this loop is not running.


Previous pytest-asyncio behaviour (use L2 to run test_client) was a problem when using fixture finalizers (https://github.com/pytest-dev/pytest-asyncio/issues/162), and that's why V0.14 tries to run test case with loop provided by event_loop. 

Can you please let me know if there  is any reason to not use loop provided by event_loop? 
Will be possible that aiohttp use same loop as event_loop?

Please let me know your kind feedback, in order to find a win-win solution. 
And don´t hesitate to ask me any support if you need any additional clarification or something else.

**Comment by Tinche** [comment]
I will also add I was under the impression `pytest-aiohttp` was slightly incompatible with `pytest-asyncio`, unfortunately. Whenever I tried using them together I ran into weird issues. Would be cool if we could make them depend on us :)

**Comment by Carsten-Leue** [comment]
Hi @alblasco , thanks a lot for looking into this. Your explanation makes sense to me. 

You write:

> Can you please let me know if there is any reason to not use loop provided by event_loop?
Will be possible that aiohttp use same loop as event_loop?

I am not affiliated with `pytest-aiohttp`, I am just an exploiter with the goal to run pytest with an aiohttp based application.

Is it possible for me to write my testcode in a way to follow your advice? If so, would you please be so kind to add this to my example code snippet?

**Comment by alblasco** [comment]
You just can try to avoid aiohttp_client fixture, see examples on https://docs.aiohttp.org/en/stable/client_quickstart.html#make-a-request

And so something similar to your example is:
```
import aiohttp
from pytest import mark

@mark.asyncio
async def test_client():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://httpbin.org/get') as resp:
            print(resp.status)
            print(await resp.text())
```

Thanks for commenting the issue in aio-libs/pytest-aiohttp#16

**Comment by Carsten-Leue** [comment]
@alblasco but that's not the equivalent of what the `test_client` from `aiohttp` is offering. The `test_client` allows you to start the application in the scope of one single test client, then run your tests and shut down the application. It would also select a free port for you, automatically. In your example you assume that the application is already running.

**Comment by serjshevchenko** [comment]
I faced with same issue, found some workaround,
override default **loop** fixture with pytest-asyncio **event_loop**
```
@pytest.fixture
def loop(event_loop):
    return event_loop
```
mark your test coro with **pytest.mark.asyncio**
```
@pytest.mark.asyncio
async def test_coro(cli, event_loop, aiohttp_client):
   app = create_app(loop=event_loop)
   cli = await aiohttp_client(app)
   await cli.get(url)
```

**Comment by seifertm** [comment]
When this issue was created, pytest-asyncio and pytest-aiohttp were incompatible with each other.

This has changed starting from pytest-aiohttp-1.0.0 (and pytest-asyncio-0.17.2). If you're experiencing problems, make sure to upgrade to the latest versions of the library and feel free to report any issue you encounter!
