### ISSUE TITLE
Don't close the loop if it's already closed

### ISSUE THREAD

**Issue by sametmax** [pytest-dev/pytest-asyncio#18]
Love the lib!

Right now I can't use it with code that closes the event loop. Could you make it so it check if loop.is_closed(), and if it is, not attempt to close (which make the test fails)?

**Comment by Tinche** [comment]
Hi,

first of all, thanks for helping make pytest-asyncio better.

I can't really reproduce this using a very simple test case. As far as I can see, closing a closed event loop should actually just do nothing, since a check for this already exists: https://github.com/python/cpython/blob/master/Lib/asyncio/selector_events.py#L95

Now, trying to close the event loop in a coroutine marked with @pytest.mark.asyncio will throw an error because the event loop is still running (RuntimeError: Cannot close a running event loop). Is this what you're seeing?

**Comment by sametmax** [comment]
Ah, yes indeed. My bad, I forgot to call stop before close. Sorry for wasting your time.

**Comment by Tinche** [comment]
No problem, no worries :)
