### ISSUE TITLE
RuntimeError: Event loop is closed after upgrade from 0.16

### ISSUE THREAD

**Issue by spacemanspiff2007** [pytest-dev/pytest-asyncio#274]
Hello,

I have an application that is both asyncio but also uses a ThreadPoolExecutor to run functions from the user.
Since I need to schedule Tasks from the thread pool, I use a global variable in my module which holds my event loop and set it up when the application starts. I then use this variable to schedule Tasks thread save (if necessary).

After the upgrade to 0.17.2 however all my tests fail since the event loop somehow gets closed and I am not sure why.
I provide a ``event_loop`` fixture which points the loop and does not close it after the tests.
But still with the new version all my tests fail because the event loop still gets closed.

```python
@pytest.yield_fixture(autouse=True, scope='function')
def event_loop():
    token = async_context.set('pytest')

    yield HABApp.core.const.loop

    async_context.reset(token)
```

So on the one hand I need to share the loop across my application because I schedule Tasks from threads and on the other hand I don't want my tests to fail.
What would be a good solution for this dilemma?

**Comment by seifertm** [comment]
Thanks for reaching out! By default `pytest-asyncio` provides one event loop per test. In order to ensure isolation between test cases a fresh event loop is provided for each test case and cleaned up when the test case finishes.

In your example you override the `event_loop` fixture, because you want to reuse a global variable, but the `scope` is set to `function`. That means pytest-asyncio will try to set up and tear down the fixture for each test resulting in a closed loop. You can verify that by running pytest with the `--setup-show` switch.

You say that you want the loop to be shared across your application, so you need to adjust the fixture scope accordingly, for example `scope="session"`. This should only tear down the fixture at the end of your test session.

Can you give that at try and report back?

**Comment by spacemanspiff2007** [comment]
Thank you for your very quick reply!
I changed the scope to ``session`` and it works as expected.

Do you have any good hint or tip how I can still achieve proper test isolation or how I can change my application?

**Comment by seifertm** [comment]
Glad to hear the session scope is working. I'll close the issue, if you don't mind.

Is there any way you can create a new instance of `HABApp.core.const.loop` rather than using a global variable? In that case, you could make the `event_loop`fixture function scoped again and each test would have their own loop and run in isolation from the others.

**Comment by spacemanspiff2007** [comment]
> I'll close the issue, if you don't mind.

Yes sure - thank you for your help!

---

> Is there any way you can create a new instance of `HABApp.core.const.loop` rather than using a global variable? In that case, you could make the `event_loop`fixture function scoped again and each test would have their own loop and run in isolation from the others.

I can create new event loop instances for testing.
However in my code I also use ```from HABApp.core.const import loop``` to import the loop variable which will still point to the old closed loop and thus some parts of the code will still fail.
Currently I only can think of two solutions:
- always use the absolute path ( ```HABApp.code.const.loop```) to get the variable. The downside is much boilerplate if I use it more often in the code
- Monkeypatch the instances of ``loop`` in all files where it is imported with the new event loop

Both seem to be some kind of hack and I am wondering if there is a better solution.
Do you have any idea?

**Comment by seifertm** [comment]
I think I understand. You're creating a specifically configured loop in [openHAB](https://github.com/spacemanspiff2007/HABApp/blob/744b928af1951f5451d07d11dac21bfe3d352723/src/HABApp/core/const/loop.py) and your code is referencing it via module imports.

Rather than putting a fixed event loop into `HABApp.code.const.loop`, you could register a [custom event loop policy](https://docs.python.org/3/library/asyncio-policy.html#custom-policies). An event loop policy is basically a loop factory. In your case, the policy would return event loops with your special configuration.

Once the policy is registered, all calls to `asyncio.new_event_loop()` and similar functions will create a new loop from your policy. Your code would no longer reference `HABApp.code.const.loop` directly. Your code would instead call `asyncio.run()` or `asyncio.get_event_loop()` as usual. I would say this is a more idiomatic way to have a customized event loop in asyncio.

Starting with `pytest-asyncio-0.17` the plugin will respect the event loop policy in the tests. That means if you register a policy for the test run, the `event_loop` fixture will return event loops produced by your policy. At this point you can try changing the scope of the fixture to `function` again.

**Comment by spacemanspiff2007** [comment]
> I think I understand. You're creating a specifically configured loop in [openHAB](https://github.com/spacemanspiff2007/HABApp/blob/744b928af1951f5451d07d11dac21bfe3d352723/src/HABApp/core/const/loop.py) and your code is referencing it via module imports.

Perfect summary. However the problem is not with creating new event loops:
I have a thread pool and some functions can be called from an async context or from within the thread pool.
So some Tasks have to be created with [run_coroutine_threadsafe](https://github.com/spacemanspiff2007/HABApp/blob/744b928af1951f5451d07d11dac21bfe3d352723/src/HABApp/core/lib/pending_future.py#L39) which then needs to current event loop passed in as an argument.
That's why I save the event loop as a variable because in the current thread there might be no event loop running and ``asyncio.get_event_loop()`` thus will fail.

**Comment by seifertm** [comment]
Hmm, I assume you want to have a single event loop for all threads, not one loop for each of them. Then I don't see any way of getting around the global reference at the moment.

I don't think it's necessarily bad to have an `event_loop` fixture with broader scope. That's why pytest-asyncio allows it in the first place.

**Comment by spacemanspiff2007** [comment]
> Hmm, I assume you want to have a single event loop for all threads

Yes - it's an asyncio application and the central event loop is the coordinator.

> I don't think it's necessarily bad to have an event_loop fixture with broader scope.

Okay, maybe I can still get rid of some of the code. I'll take a look at it.
Thank you very much for you kind help!
