### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frenzymadness** [pytest-dev/pytest-asyncio#443]
Hello.

Do you plan to release a new version? The compatibility with pytest 7.2.0 is very useful for me.

**Comment by seifertm** [comment]
pytest-asyncio v0.20.2 has been released, which gets rid of some deprecation warnings raised by pytest v7.2.

I encourage you to continue asking about releasing merged changes in the future. Sometimes that reminder is necessary :) I would appreciate, if you could do that in the corresponding PR or in a discussion, instead of creating a new issue, though.
