### ISSUE TITLE
All async fixtures must be scoped to a function

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-asyncio#75]
I have a session scoped fixture that runs a Postgres database in the background.
I'd like the connection pool to that database to last for the entire session for the entire session as well.

This fails because the event_loop fixture is scoped to a function.

Is there a workaround for this problem?

**Comment by Tinche** [comment]
Hm, can you try to redefine the event_loop fixture to be session scoped too? (The README mentions this under Async fixtures.) 

You can just copy/paste the event_loop fixture from https://github.com/pytest-dev/pytest-asyncio/blob/master/pytest_asyncio/plugin.py#L177

**Comment by nicoddemus** [comment]
Alternatively, perhaps the `pytest-asyncio`'s event_loop fixture should be changed to be session-scoped? I suppose one of the reasons for it to be function-scoped is to avoid events to leak between tests, but is there a way to "flush" the event loop to ensure it doesn't have tasks still running? If so, it is possible to have a function-scoped fixture which "flushes" the event loop:

```python

@pytest.fixture(scope='session')
def event_loop():
    ...

@pytest.fixture
def _flush_event_loop(event_loop):
    yield
    event_loop.flush()
```

This way we can inject `_flush_event_loop` instead of `event_loop` into the fixture definitions during `pytest_fixture_setup`.

**Comment by asvetlov** [comment]
No, asyncio has no `flush` functionality intentionally -- it is too error prone.
N.B. 
Not only tasks should be flushed but open sockets and other file descriptors, scheduled callbacks and unclosed async generators (the list might be extended in next asyncio releases).

**Comment by nicoddemus** [comment]
I didn't mean "flush" as interrupting running tasks, more something along the lines of `loop.run_remaining_tasks()` or something like that. I agree a function that would just terminate tasks would be error prone.

**Comment by asvetlov** [comment]
`run_remaining_tasks` doesn't exist also -- and I pretty sure the method will be never added.

**Comment by nicoddemus** [comment]
I see, thanks @asvetlov.

**Comment by thedrow** [comment]
Could something like [this](https://stackoverflow.com/a/27910822/85140) do the trick?

**Comment by asvetlov** [comment]
No. As I said not only running tasks but other things like open sockets and scheduled callbacks should be counted.

**Comment by thedrow** [comment]
Just wondering, doesn't `Task.all_tasks()` include all of those?

**Comment by fivepapertigers** [comment]
FYI - this can probably be closed, since a workaround exists (redefining the `event_loop` fixture).

That said, it may be nice to at least provide a simpler way to change the scope without having to redefine the fixture - especially since it risks drift in implementation. Someone's overridden fixture could easily drift from `pytest-asyncio`'s implementation if a change is made in the latter.
