### ISSUE TITLE
Conflicting `pytest-aiohttp` and `pytest-asyncio`

### ISSUE THREAD

**Issue by vlcinsky** [pytest-dev/pytest-asyncio#76]
See the https://github.com/aio-libs/pytest-aiohttp/issues/8 

I am not sure, if it is fault of one or the other plugin or there is a need on some naming convention not to clash one with another.

Personally I consider `pytest-asyncio` more general and would expect a fix on `pytest-aiohttp` side, but this is too early to tell before the reason is well described.

**Comment by butla** [comment]
I noticed that today and removed pytest-asyncio, since I didn't know why I had it installed anyway. Or maybe it was doing something that `pytest-aiohttp` wasn't doing at some point.

The specific problem I was experiencing was that a `pytest-asyncio`'s loop was my `async` fixtures, while a loop from `pytest-aiohttp` was running my `async` tests.

I guess a good solution would be to add great coroutine testing support to `pytest` itself, but yeah, I'm as lasy as anyone so I don't see myself doing that anytime soon.

**Comment by asvetlov** [comment]
Fixed by pytest-asyncio 0.17 and pytest-aiohttp 1.0
