### ISSUE TITLE
async fixtures are incompatible with pytest 3.7.0

### ISSUE THREAD

**Issue by brycedrennan** [pytest-dev/pytest-asyncio#89]
Not sure exactly what the issue is yet but test suite passes in pytest==3.6.* but fails in the very recently released pytest 3.7.0.

**Comment by Gr1N** [comment]
Got same issue, any ideas?

**Comment by brycedrennan** [comment]
For now I've just pinned my pytest to 3.6.4

**Comment by jwldk** [comment]
Same problem here. Get this error:

`E       TypeError: 'coroutine' object is not subscriptable`

when trying to use a async fixture in a test. Works with pytest 3.6.4. Doesn't even appear to be anything related in the pytest changelog.

**Comment by JohanLorenzo** [comment]
I got a similar error. I filed this issue in pytest https://github.com/pytest-dev/pytest/issues/3747 (more details in there). @RonnyPfannschmidt suggested to open an issue over here. I put up a minimal test case https://github.com/JohanLorenzo/pytest-fixture-bug-3747. Please let me know if I can provide more details.

**Comment by RonnyPfannschmidt** [comment]
@jwldk fixture definition changed in pytest to give a deprecationwarning on non-fixture usage, this issue is a collateral of that

**Comment by nicoddemus** [comment]
I investigated and here's the problem:

https://github.com/pytest-dev/pytest-asyncio/blob/1ada09670936071a6b72abf064e00ebe6a9fff5e/pytest_asyncio/plugin.py#L45-L50

In pytest 3.7.0 `fixturef.func` is the "wrapped" function (which issues the warning when calling directly), which is not a coroutine/async function. This of course breaks this code.

@RonnyPfannschmidt unless we find a solution to this I'm considering reverting the wrapping code. `pytest-asyncio` probably is not the only plugin that will break because of this I'm afraid. 😟
